# Generated by Django 4.2.6 on 2023-10-12 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
